#!/usr/bin/env node
/*
 * Bundles the ES modules under scripts/ into a single classic (non-module)
 * script, scripts/app.bundle.js, so the app runs by double-clicking
 * index.html (file://) — where browsers block ES modules but allow classic
 * scripts, <img>, and CSS. Run `node build.js` after editing any module.
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SCRIPTS = path.join(ROOT, 'scripts');
const ENTRY = 'scripts/app.js';

function listJs(dir) {
  const out = [];
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) out.push(...listJs(full));
    else if (name.endsWith('.js') && name !== 'app.bundle.js') out.push(full);
  }
  return out;
}

function modId(absPath) {
  return path.relative(ROOT, absPath).split(path.sep).join('/');
}

function resolveImport(fromFile, spec) {
  const abs = path.resolve(path.dirname(fromFile), spec);
  return modId(abs);
}

function transform(absPath) {
  let src = fs.readFileSync(absPath, 'utf8');
  const exportsNames = new Set();

  // import * as ns from '...'
  src = src.replace(/^import\s+\*\s+as\s+(\w+)\s+from\s+['"]([^'"]+)['"];?/gm,
    (_m, ns, spec) => `const ${ns} = __require(${JSON.stringify(resolveImport(absPath, spec))});`);

  // import { a, b } from '...'  (may span multiple lines)
  src = src.replace(/^import\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"];?/gm,
    (_m, names, spec) => `const {${names}} = __require(${JSON.stringify(resolveImport(absPath, spec))});`);

  // export { a, b };
  src = src.replace(/^export\s*\{([^}]*)\};?/gm, (_m, names) => {
    names.split(',').map((s) => s.trim()).filter(Boolean).forEach((n) => exportsNames.add(n));
    return '';
  });

  // export const NAME / export function NAME / export class NAME
  src = src.replace(/^export\s+(const|let|var|function|class)\s+([A-Za-z0-9_$]+)/gm,
    (_m, kind, name) => { exportsNames.add(name); return `${kind} ${name}`; });

  const tail = [...exportsNames].map((n) => `exports.${n} = ${n};`).join('\n');
  return `__def(${JSON.stringify(modId(absPath))}, function(module, exports, __require){\n${src}\n${tail}\n});`;
}

const files = listJs(SCRIPTS).sort();
const runtime = `/* AUTO-GENERATED by build.js — do not edit. Bundles scripts/ for file:// use. */
(function(){
  var __mods = {}, __cache = {};
  function __def(id, fn){ __mods[id] = fn; }
  function __require(id){
    if (__cache[id]) return __cache[id].exports;
    var m = { exports: {} };
    __cache[id] = m;
    if (!__mods[id]) throw new Error('module not found: ' + id);
    __mods[id](m, m.exports, __require);
    return m.exports;
  }
`;
const body = files.map(transform).join('\n\n');
const boot = `\n  __require(${JSON.stringify(ENTRY)});\n})();\n`;

fs.writeFileSync(path.join(SCRIPTS, 'app.bundle.js'), runtime + body + boot);
console.log(`bundled ${files.length} modules -> scripts/app.bundle.js`);
